version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql_tibo
    restart: always
    env_file:
      - .env
    ports:
      - '3307:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - tibo_network

networks:
  my-network:
    driver: bridge

volumes:
  mysql-data:
